implement service discovery
apache/dubbo-rust pull request #103
Opened 2023-01-19 09:52 UTC by robberphex

You may call `client.with_directory(Box::new(StaticDirectory::new(&host)))` to call a static host.

2023-01-23 03:20 UTC, yang20150702 commented on dubbo/src/invocation.rs
> +
implementation of RpcInvocation is too complicated. Now we can use a struct as metadata. In future, we can rebuild this struct by new requirements

2023-01-23 03:20 UTC, yang20150702 commented on dubbo/src/triple/client/triple.rs
> +
Dubbo的一个特性是配置优先。我建议可以将服务发现相关的配置放到clientBuilder中，通过配置来启动服务发现；这样可以简化dubbo-build侧client生成的代码
另外，自定义配置directory应该是高级能力。

2023-02-09 11:56 UTC, AlbumenJ requested changes

2023-02-09 11:56 UTC, AlbumenJ commented on dubbo-build/src/client.rs
> +                // }
remove

2023-02-09 12:10 UTC, AlbumenJ approved these changes

2023-02-09 12:10 UTC, merged